# ╔══════════════════════════════════╗
# ║           𝔸𝕡𝕡𝕝𝕚𝕔𝕒𝕥𝕚𝕠𝕟𝕤           ║
# ╚══════════════════════════════════╝

$terminal = kitty
$fileManager = kitty yazi
$menu = rofi -show drun -config ~/.config/rofi/drun.rasi
$browser = zen-browser
