# ╔══════════════════════════════════╗
# ║           𝔸𝕡𝕡𝕝𝕚𝕔𝕒𝕥𝕚𝕠𝕟𝕤           ║
# ╚══════════════════════════════════╝

$terminal = kitty
$fileManager = kitty yazi
$menu = rofi -show drun -drun-display-format "{name}  <span size='small' font-family='SF Compact Display' alpha='50%'> •   {comment}</span>" -mesg "↑↓ navigate   ↵ open   Esc close" -theme-str "listview {lines: 4;} window {width: 680px;} element {border: 1px 0px 0px 0px;}"
$browser = zen-browser
