# ╔══════════════════════════════════╗
# ║            𝔸𝕦𝕥𝕠𝕤𝕥𝕒𝕣𝕥             ║
# ╚══════════════════════════════════╝

# Autostart
exec-once = waybar & hyprpaper & hyprsunset & swaync
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = sleep 5 && rclone mount drive: /mnt/drive --vfs-cache-mode writes &
exec-once = sleep 3 && nvibrant 307 307
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
