# ╔══════════════════════════════════╗
# ║              ℝ𝕦𝕝𝕖𝕤               ║
# ╚══════════════════════════════════╝

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Example windowrules that are useful
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Make steam and its fl tile
windowrule {
  name = tile-steam
  match:class = steam
  match:title = ^(Steam|Friends List|.* - Steam)$
  tile = yes
}

# Tile minecraft
windowrule {
  name = tile-minecraft
  match:class = Minecraft.*
  tile = yes
}

# Fix fallout 76
windowrule {
  name = fix-fallout76
  match:class = steam_app_1151340
  float = yes
  size = 1920 1080
  move = 0 0
}

# Layer rules
layerrule {
  name = waybar_default
  match:namespace = waybar

  blur = on
  ignore_alpha = 0.2
}

layerrule {
  name = rofi_default
  match:namespace = rofi

  blur = on
  ignore_alpha = 0.2
}

layerrule {
  name = swaync_control-center
  match:namespace = swaync-control-center

  blur = on
  ignore_alpha = 0.4
}

layerrule {
  name = swaync_notification
  match:namespace = swaync-notification-window

  blur = on
  ignore_alpha = 0.4
}
