$base = rgb(2e3440)
$baseAlpha = 2e3440
$mantle = rgb(2e3440)
$mantleAlpha = 2e3440
$crust = rgb(2e3440)
$crustAlpha = 2e3440
$surface0 = rgb(3b4252)
$surface0Alpha = 3b4252
$surface1 = rgb(434c5e)
$surface1Alpha = 434c5e
$surface2 = rgb(4c566a)
$surface2Alpha = 4c566a
$text = rgb(eceff4)
$textAlpha = eceff4
$subtext1 = rgb(e5e9f0)
$subtext1Alpha = e5e9f0
$subtext0 = rgb(d8dee9)
$subtext0Alpha = d8dee9
$overlay2 = rgb(d8dee9)
$overlay2Alpha = d8dee9
$overlay1 = rgb(4c566a)
$overlay1Alpha = 4c566a
$overlay0 = rgb(434c5e)
$overlay0Alpha = 434c5e
$rosewater = rgb(8fbcbb)
$rosewaterAlpha = 8fbcbb
$flamingo = rgb(88c0d0)
$flamingoAlpha = 88c0d0
$pink = rgb(b48ead)
$pinkAlpha = b48ead
$mauve = rgb(b48ead)
$mauveAlpha = b48ead
$red = rgb(bf616a)
$redAlpha = bf616a
$maroon = rgb(d08770)
$maroonAlpha = d08770
$peach = rgb(d08770)
$peachAlpha = d08770
$yellow = rgb(ebcb8b)
$yellowAlpha = ebcb8b
$green = rgb(a3be8c)
$greenAlpha = a3be8c
$teal = rgb(8fbcbb)
$tealAlpha = 8fbcbb
$sky = rgb(88c0d0)
$skyAlpha = 88c0d0
$sapphire = rgb(81a1c1)
$sapphireAlpha = 81a1c1
$blue = rgb(5e81ac)
$blueAlpha = 5e81ac
$lavender = rgb(81a1c1)
$lavenderAlpha = 81a1c1
