config_version = 14

[bar.default]
center = [ "media", "wallpaper", "clock", "weather" ]
end = [
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_ends = 0
radius = 0
radius_bottom_left = 6
radius_bottom_right = 6
start = [ "launcher", "input_volume", "workspaces" ]
thickness = 26

[calendar]

[control_center.calendar]
show_events_card = false

[dock]
layer = "overlay"
reserve_space = false

[location]
address = "RJ, Brazil"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_night = 5000

[osd]
enabled = false

[shell]
font_family = "SF Pro Display"

    [shell.launcher]
    categories = false
    compact = true

[theme]
builtin = "Ayu"
community_palette = "Zenbones"
custom_palette = "Vague"
mode = "dark"
source = "custom"

[wallpaper.default]
path = "/home/vitt/Pictures/pictures/pics/wallpapers/thumb-1920-787745.png"

[wallpaper.last]
path = "/home/vitt/Pictures/pictures/pics/wallpapers/thumb-1920-787745.png"

[wallpaper.monitors.DP-1]
path = "/home/vitt/Pictures/pictures/pics/wallpapers/thumb-1920-787745.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/vitt/Pictures/pictures/pics/wallpapers/thumb-1920-787745.png"

[widget.clock]
anchor = true
format = "{:%d • %I:%M %p}"

[widget.input_volume]
show_label = false

[widget.launcher]
glyph = "brand-apple-filled"

[widget.media]
title_scroll = "always"

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.weather]
show_condition = false

[widget.workspaces]
occupied_color = "tertiary"