# reload config with prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf
# change prefix to Ctrl+Space
set -g prefix C-Space
# enable mouse support
set -g mouse on
set -s set-clipboard on
# start window numbering at 1
set -g base-index 1
# remove delay on esc in nvim
set -sg escape-time 0
# remove panel kill confirmation
bind-key x kill-pane
# vim-style pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# yazi recommended config for tmux
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# renumber windows when one is closed
set -g renumber-windows on

# # status bar
# set -g status on
# set -g status-justify absolute-centre
# set -g status-style "bg=default,fg=white"
#
# # left: prefix indicator - lights up when prefix is active
# set -g status-left "#{?client_prefix,#[bg=brightcyan fg=black bold]  on  ,#[fg=brightcyan bg=black]  off } #[fg=brightblue bg=black] 󰉋 #{b:pane_current_path}/ "
# set -g status-left-length 20
#
# # right: hostname
# set -g status-right "#[fg=brightmagenta bg=black]  #H #[fg=white]"
# set -g status-right-length 30
#
# # window list styling
# set -g window-status-separator ""
# set -g window-status-format "#[fg=brightwhite,bg=black] #I:#W "
# set -g window-status-current-format "#[fg=black,bg=brightwhite] #I:#W "

set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "white"
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-status-right "#H  "

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run ~/.tmux/plugins/tpm/tpm
