[General]
# Colors
backgroundFill=#1e1e2e
basicTextColor=#cdd6f4
passwordCursorColor=#cdd6f4
passwordInputBackground=#1e1e2e
passwordTextColor=#cdd6f4

# Characters
passwordCharacter=*
passwordMask=true
passwordFontSize=96

# Cursor
passwordInputCursorVisible=true
cursorBlinkAnimation=true

# Sessions
showSessionsByDefault=false
sessionsFontSize=24

# Users
showUsersByDefault=false
usersFontSize=48
showUserRealNameByDefault=true
