[colors]
background = #171719
foreground = #cdcdcd
secondary  = #606079
black = #141415
shadow = #1c1c24
graphite = #252530
onyx = #333738
muted = #606079
gray = #878787
white = #cdcdcd
yellow = #f3be7c
amber = #e8b589
gold = #e0a363
peach = #c48282
red = #d8647e
storm = #405065
lilac = #c3c3d5
cyan = #aeaed1
magenta = #bb9dbd
aqua = #b4d4cf
lavender = #90a0b5
teal = #9bb4bc
blue = #6e94b2
iris = #7e98e8
green = #7fa563

[bar/main]
width = 100%
height = 28
radius = 0
border-size = 0
monitor = DP-0
background = ${colors.background}
foreground = ${colors.foreground}
module-margin = 0
# font-N are referenced elsewhere via a 1-BASED index:
# font-0 -> index 1, font-1 -> index 2, font-2 -> index 3
font-0 = SF Compact Display:style=Bold:size=10;2
font-1 = FiraCode Nerd Font Propo:style=Bold:size=10;2
font-2 = FiraCode Nerd Font Propo:style=SemiBold:size=8;2
font-3 = SF Compact Display:style=SemiBold:size=11;2
modules-left = mic i3
modules-center = date
modules-right = systray mudfish network bluetooth volume
enable-ipc = true
cursor-click = pointer

[module/date]
type = internal/date
interval = 1
date = %d
time = %I:%M %p
format = <label>
format-foreground = ${colors.foreground}
label = %date%  •  %time%
format-font = 4

[module/i3]
type = internal/i3
format-font = 2

# pin workspaces to their assigned monitors
pin-workspaces = true

label-focused = %name%
label-focused-foreground = ${colors.white}
label-focused-padding = 1
label-visible = %name%
label-visible-foreground = ${colors.white}
label-visible-padding = 1
label-unfocused = 
label-unfocused-padding = 1
label-urgent = 
label-urgent-foreground = ${colors.background}
label-urgent-padding = 1

[module/systray]
type = internal/tray
format-margin = 4
tray-spacing = 4pt
tray-background = ${colors.background}

[module/volume]
type = internal/pulseaudio
format-volume-font = 1
format-margin = 2
format-volume = vol <label-volume>%
label-volume = %percentage%
label-muted = muted
label-muted-font = 1
click-right = pavucontrol
format-volume-margin = 4

[module/network]
type = internal/network
interface = enp4s0
interval = 3
format-connected-font = 1
format-connected = ethernet
format-connected-margin = 4
format-disconnected-font = 1
format-disconnected = disconnected
format-disconnected-margin = 4

[module/bluetooth]
type = custom/text
label = bluetooth
label-font = 1
click-left = blueman-manager &

[module/mic]
type = custom/script
exec = ~/.config/polybar/src/mic.sh
tail = true
interval = -1 # Decoupled from time-based loops; only updates when told
format-padding = 3
format-foreground = ${colors.foreground}
label-font = 3
click-left = pactl set-source-mute @DEFAULT_SOURCE@ toggle && polybar-msg action #mic.hook.0

[module/mudfish]
type = custom/script
exec = ~/.local/bin/polymud-status.sh
tail = true
interval = 5
click-left = ~/.local/bin/mudfish-start.sh
click-right = ~/.local/bin/mudfish-stop.sh
format-prefix = ""
format-margin = 0
label-font = 1

[bar/main-secondary]
inherit = bar/main
monitor = HDMI-0
