$base = rgba(141415aa)
$baseAlpha = 141415
$mantle = rgba(131313aa)
$mantleAlpha = 131313
$crust = rgba(11111baa)
$crustAlpha = 11111b
$surface0 = rgba(252530aa)
$surface0Alpha = 252530
$surface1 = rgba(333738aa)
$surface1Alpha = 333738
$surface2 = rgba(405065aa)
$surface2Alpha = 405065
$text = rgba(f0f0f0aa)
$textAlpha = f0f0f0
$subtext1 = rgba(b4d4cfaa)
$subtext1Alpha = b4d4cf
$subtext0 = rgba(90a0b5aa)
$subtext0Alpha = 90a0b5
$overlay2 = rgba(878787aa)
$overlay2Alpha = 878787
$overlay1 = rgba(606079aa)
$overlay1Alpha = 606079
$overlay0 = rgba(252530aa)
$overlay0Alpha = 252530
$rosewater = rgba(efefdcaa)
$rosewaterAlpha = efefdc
$flamingo = rgba(f7d498aa)
$flamingoAlpha = f7d498
$pink = rgba(bb9dbdaa)
$pinkAlpha = bb9dbd
$mauve = rgba(b0a0d0aa)
$mauveAlpha = b0a0d0
$red = rgba(d8647eaa)
$redAlpha = d8647e
$maroon = rgba(c48482aa)
$maroonAlpha = c48482
$peach = rgba(e0a363aa)
$peachAlpha = e0a363
$yellow = rgba(f3be7caa)
$yellowAlpha = f3be7c
$green = rgba(7fa563aa)
$greenAlpha = 7fa563
$teal = rgba(b4d4cfaa)
$tealAlpha = b4d4cf
$sky = rgba(9bb4bcaa)
$skyAlpha = 9bb4bc
$sapphire = rgba(6e94b2aa)
$sapphireAlpha = 6e94b2
$blue = rgba(7e98e8aa)
$blueAlpha = 7e98e8
$lavender = rgba(aeaed1aa)
$lavenderAlpha = aeaed1
