$base = rgb(141415)
$baseAlpha = 141415
$mantle = rgb(131313)
$mantleAlpha = 131313
$crust = rgb(11111b)
$crustAlpha = 11111b
$surface0 = rgb(1c1c24)
$surface0Alpha = 1c1c24
$surface1 = rgb(252530)
$surface1Alpha = 252530
$surface2 = rgb(333738)
$surface2Alpha = 333738
$text = rgb(cdcdcd)
$textAlpha = cdcdcd
$subtext1 = rgb(b4d4cf)
$subtext1Alpha = b4d4cf
$subtext0 = rgb(90a0b5)
$subtext0Alpha = 90a0b5
$overlay2 = rgb(878787)
$overlay2Alpha = 878787
$overlay1 = rgb(606079)
$overlay1Alpha = 606079
$overlay0 = rgb(252530)
$overlay0Alpha = 252530
$rosewater = rgb(efefdc)
$rosewaterAlpha = efefdc
$flamingo = rgb(f7d498)
$flamingoAlpha = f7d498
$pink = rgb(bb9dbd)
$pinkAlpha = bb9dbd
$mauve = rgb(c3c3d5)
$mauveAlpha = c3c3d5
$red = rgb(d8647e)
$redAlpha = d8647e
$maroon = rgb(c48282)
$maroonAlpha = c48282
$peach = rgb(e0a363)
$peachAlpha = e0a363
$yellow = rgb(f3be7c)
$yellowAlpha = f3be7c
$green = rgb(7fa563)
$greenAlpha = 7fa563
$teal = rgb(6e94b2)
$tealAlpha = 6e94b2
$sky = rgb(9bb4bc)
$skyAlpha = 9bb4bc
$sapphire = rgb(aeaed1)
$sapphireAlpha = aeaed1
$blue = rgb(7e98e8)
$blueAlpha = 7e98e8
$lavender = rgb(c3c3d5)
$lavenderAlpha = c3c3d5
