$bg = rgb(141415)
$bgAlpha = 141415
$bg-inactive = rgb(1c1c24)
$bg-inactiveAlpha = 1c1c24
$bg-line = rgb(252530)
$bg-lineAlpha = 252530
$fg = rgb(cdcdcd)
$fgAlpha = cdcdcd
$border = rgb(878787)
$borderAlpha = 878787
$comment = rgb(606079)
$commentAlpha = 606079
$cyan = rgb(b4d4cf)
$cyanAlpha = b4d4cf
$red = rgb(c48282)
$redAlpha = c48282
$orange = rgb(e8b589)
$orangeAlpha = e8b589
$yellow = rgb(e0a363)
$yellowAlpha = e0a363
$blue = rgb(c3c3d5)
$blueAlpha = c3c3d5
$purple = rgb(aeaed1)
$purpleAlpha = aeaed1
$magenta = rgb(bb9dbd)
$magentaAlpha = bb9dbd
$visual = rgb(333738)
$visualAlpha = 333738
$error = rgb(d8647e)
$errorAlpha = d8647e
$warning = rgb(f3be7c)
$warningAlpha = f3be7c
$hint = rgb(7e98e8)
$hintAlpha = 7e98e8
$operator = rgb(90a0b5)
$operatorAlpha = 90a0b5
$keyword = rgb(6e94b2)
$keywordAlpha = 6e94b2
$type = rgb(9bb4bc)
$typeAlpha = 9bb4bc
$search = rgb(405065)
$searchAlpha = 405065
$green = rgb(7fa563)
$greenAlpha = 7fa563
$delta = rgb(f3be7c)
$deltaAlpha = f3be7c

