#!/usr/bin/env bash
if pgrep -u root mudrun-headless > /dev/null 2>&1; then
  text="<span color='#7e98e8'>\ue32a</span>"
  tip="Mudfish VPN is ON"
  cls="on"
else
  text="\ue32a"
  tip="Mudfish VPN is OFF"
  cls="off"
fi
printf '{"text":"%s","tooltip":"%s","class":"%s","markup":"pango"}\n' \
  "$text" "$tip" "$cls"
