# ╔══════════════════════════════════╗
# ║             ℍ𝕪𝕡𝕣𝕝𝕒𝕟𝕕             ║
# ╚══════════════════════════════════╝

source = ~/.config/hypr/mocha.conf
source = ~/.config/hypr/src/env.conf
source = ~/.config/hypr/src/monitors.conf
source = ~/.config/hypr/src/apps.conf
source = ~/.config/hypr/src/autostart.conf
source = ~/.config/hypr/src/appearance.conf
source = ~/.config/hypr/src/input.conf
source = ~/.config/hypr/src/binds.conf
source = ~/.config/hypr/src/workspaces.conf
source = ~/.config/hypr/src/rules.conf
