splash = false

wallpaper {
  monitor = DP-1
  path = ~/Pictures/pictures/pics/hyprland/hyprpaper/wallhaven-l8mxeq_1920x1080.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Pictures/pictures/pics/hyprland/hyprpaper/wallhaven-l8mxeq_1920x1080.png
  fit_mode = cover
}
